name: 개발 서버 배포

on:
  push:
    branches:
      - dev
      - config/122-deploy-script

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      restaurant-exposure: ${{ steps.filter.outputs.restaurant-exposure }}
      search: ${{ steps.filter.outputs.search }}
      cache: ${{ steps.filter.outputs.cache }}
      advertisement: ${{ steps.filter.outputs.advertisement }}
      coupon: ${{ steps.filter.outputs.coupon }}
      delivery-time: ${{ steps.filter.outputs.delivery-time }}
      restaurant: ${{ steps.filter.outputs.restaurant }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            restaurant-exposure:
              - 'service/restaurant-exposure-service/**'
            search:
              - 'service/search-service/**'
            cache:
              - 'service/cache-service/**'
            advertisement:
              - 'service/advertisement-service/**'
            coupon:
              - 'service/coupon-service/**'
            delivery-time:
              - 'service/delivery-time-service/**'
            restaurant:
              - 'service/restaurant-service/**'

  build:
    needs: changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: JDK 21 설정
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'zulu'
      - name: gradlew 실행 권한 부여
        run: chmod +x gradlew
      - name: JAR 빌드
        run: ./gradlew clean build

  deploy-restaurant-exposure:
    needs: [ changes, build ]
    if: ${{ needs.changes.outputs.restaurant-exposure == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 가게노출 서비스 서버로 JAR 전송
        env:
          PRIVATE_KEY: ${{ secrets.DEV_EC2_SSH_KEY }}
          HOST: ${{ secrets.DEV_EC2_HOST1 }}
          USER: ${{ secrets.DEV_EC2_USER }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          scp -o StrictHostKeyChecking=no -i private_key service/restaurant-exposure-service/build/libs/*.jar ${USER}@${HOST}:~/restaurant-exposure-service.jar
      - name: 가게노출 서비스 실행
        env:
          PRIVATE_KEY: ${{ secrets.DEV_EC2_SSH_KEY }}
          HOST: ${{ secrets.DEV_EC2_HOST1 }}
          USER: ${{ secrets.DEV_EC2_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} << EOF
            pkill -f 'java -jar restaurant-exposure-service.jar' || true
            nohup java -jar restaurant-exposure-service.jar --spring.profiles.active=dev > restaurant-exposure-service.log 2>&1 &
          EOF

  deploy-search:
    needs: [ changes, build ]
    if: ${{ needs.changes.outputs.search == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 검색 서비스 서버로 JAR 전송
        env:
          PRIVATE_KEY: ${{ secrets.DEV_EC2_SSH_KEY }}
          HOST: ${{ secrets.DEV_EC2_HOST2 }}
          USER: ${{ secrets.DEV_EC2_USER }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          scp -o StrictHostKeyChecking=no -i private_key service/search-service/build/libs/*.jar ${USER}@${HOST}:~/search-service.jar
      - name: 검색 서비스 실행
        env:
          PRIVATE_KEY: ${{ secrets.DEV_EC2_SSH_KEY }}
          HOST: ${{ secrets.DEV_EC2_HOST2 }}
          USER: ${{ secrets.DEV_EC2_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} << EOF
            pkill -f 'java -jar search-service.jar' || true
            nohup java -jar search-service.jar --spring.profiles.active=dev > search-service.log 2>&1 &
          EOF

  deploy-other-services:
    needs: [ changes, build ]
    if: ${{ needs.changes.outputs.cache == 'true' || needs.changes.outputs.advertisement == 'true' || needs.changes.outputs.coupon == 'true' || needs.changes.outputs.delivery-time == 'true' || needs.changes.outputs.restaurant == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 기타 서비스 서버로 JAR 전송 및 실행
        env:
          PRIVATE_KEY: ${{ secrets.DEV_EC2_SSH_KEY }}
          HOST: ${{ secrets.DEV_EC2_HOST3 }}
          USER: ${{ secrets.DEV_EC2_USER }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          services=("cache" "advertisement" "coupon" "delivery-time" "restaurant")
          for service in "${services[@]}"; do
            if [[ "${{ needs.changes.outputs[format('{0}', service)] }}" == 'true' ]]; then
              scp -o StrictHostKeyChecking=no -i private_key service/${service}-service/build/libs/*.jar ${USER}@${HOST}:~/${service}-service.jar
              ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} << EOF
                pkill -f 'java -jar ${service}-service.jar' || true
                nohup java -jar ${service}-service.jar --spring.profiles.active=dev > ${service}-service.log 2>&1 &
              EOF
            fi
          done
          rm -f private_key
